name: build-pr
on:
  pull_request_target:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - master
jobs:
  build-and-deploy-pr:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Get the pull request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Save XML
        run: echo Spoon

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update XML
        run: echo "Another spoon"

      - name: Build specifications
        run: |
          ./gradlew
