name: build-specs
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y rsync

      # We’re going to be updating the gh-pages branch, but that
      # happens from two repositories. We must preserve what we
      # don’t change by getting the current version
      - name: Checkout current gh-pages
        uses: actions/checkout@v3
        with:
          repository: ndw/TransientTestingAlso
          ref: gh-pages
          path: build/dist

      - name: what have we got
        run: |
          ls -la
          ls -la build/dist

      - name: Preserve gh-pages
        run: |
          mkdir /tmp/save-gh-pages
          rsync -var --exclude .git build/dist/ /tmp/save-gh-pages/

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore current gh-pages
        run: |
          mkdir -p build/dist
          rsync -var /tmp/save-gh-pages/ build/dist/
          rm -rf /tmp/save-gh-pages

      - name: what have we got now
        run: |
          ls -la
          ls -la build/dist

