name: build-specs
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y rsync

      # We’re going to be updating the gh-pages branch, but that
      # happens from two repositories. We must preserve what we
      # don’t change by getting the current version
      - name: Checkout current gh-pages from ndw/TransientTestingAlso
        uses: actions/checkout@v3
        with:
          repository: ndw/TransientTestingAlso
          ref: gh-pages
          path: build/dist

      - name: Preserve the current gh-pages
        run: |
          mkdir /tmp/publish-gh-pages
          rsync -var --exclude .git build/dist/ /tmp/publish-gh-pages/

      - name: Checkout this repository
        uses: actions/checkout@v3

      # The temptation here is to copy the saved gh-pages back
      # into build/dist and run the build. On my local machine, that
      # adds the new files and leaves the old ones unchanged. But
      # when run as a GitHub workflow, the saved gh-pages files
      # in build/dist are deleted. I have no idea why. So instead,
      # we’ll publish from the tmp directory...

      - name: Build the specifications
        run: |
          ./gradlew

      - name: Update the publish pages
        run: rsync -var build/dist/ /tmp/publish-gh-pages/

      - name: Deploy to gh-pages on ndw/TransientTestingAlso
        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /tmp/publish-gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ndw/TransientTestingAlso
          branch: gh-pages
          target-folder: /${{ github.ref_name }}/head
