name: build-specs
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      # We’re going to be updating the gh-pages branch, but that
      # happens from two repositories. We must preserve what we
      # don’t change by getting the current version
      - name: Checkout current gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: build/dist

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./gradlew

      - name: Deploy to branch
        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ndw/TransientTestingAlso
          branch: gh-pages
          target-folder: /${{ github.ref_name }}/head
